name: github pages

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Python and cache dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build all
        run: |
          for f in $(find . -name makefile);do
            make -j2 -C $(dirname $f)
          done
          rm .gitignore
          rm -rf .git

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .